// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atpvnestmbysfyccrmej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0cHZuZXN0bWJ5c2Z5Y2NybWVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDEwODcsImV4cCI6MjA3MTc3NzA4N30._P46ffjsx1L0jWpBXFwzdsTWlWeemfUjGsESTkVp0jU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});